void default_function_kernel(float* compute, float* data) {
  #pragma omp parallel for
  for (int32_t i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused = 0; i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused < 600; ++i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused) {
    float T_softmax_maxelem[3];
    float compute_1[3];
    for (int32_t i1 = 0; i1 < 3; ++i1) {
      T_softmax_maxelem[i1] = -3.402823e+38f;
      for (int32_t k = 0; k < 15; ++k) {
        T_softmax_maxelem[i1] = max(T_softmax_maxelem[i1], data[((((((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused / 200) * 1800) + ((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused % 10) * 180)) + (i1 * 60)) + (((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused % 200) / 50) * 15)) + k)]);
      }
    }
    for (int32_t i1_1 = 0; i1_1 < 3; ++i1_1) {
      compute_1[i1_1] = 0.000000e+00f;
      for (int32_t k_1 = 0; k_1 < 15; ++k_1) {
        compute_1[i1_1] = (compute_1[i1_1] + expf((data[((((((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused / 200) * 1800) + ((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused % 10) * 180)) + (i1_1 * 60)) + (((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused % 200) / 50) * 15)) + k_1)] - T_softmax_maxelem[i1_1])));
      }
    }
    for (int32_t i3_outer_inner = 0; i3_outer_inner < 3; ++i3_outer_inner) {
      for (int32_t i1_inner = 0; i1_inner < 3; ++i1_inner) {
        compute[((((((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused / 200) * 1800) + ((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused % 10) * 180)) + (i1_inner * 60)) + (((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused % 200) / 10) * 3)) + i3_outer_inner)] = ((data[((((((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused / 200) * 1800) + ((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused % 10) * 180)) + (i1_inner * 60)) + (((i0_outer_outer_outer_i1_outer_outer_outer_fused_i2_outer_outer_outer_fused_i3_outer_outer_outer_fused_i0_outer_outer_inner_fused_i1_outer_outer_inner_fused_i2_outer_outer_inner_fused_i3_outer_outer_inner_fused_i0_outer_inner_fused_i1_outer_inner_fused_i2_outer_inner_fused % 200) / 10) * 3)) + i3_outer_inner)] - T_softmax_maxelem[i1_inner]) - logf(compute_1[i1_inner]));
      }
    }
  }
}

